### ISSUE TITLE
Missing application.css in app folder

### ISSUE THREAD

**Issue by petrk94** [anna-wro/todo#1]
Hello,
I have tried to use it, but
<link rel="stylesheet" href="css/application.css"> in the index.html in the app folder doesnt can be found, only the jquery version works.

**Comment by anna-wro** [comment]
Hi @petrk94! That was because I included only sass folder in the repository. Application.css would show only after running `gulp build` and compiling all the .sass files.
I included the css file in my latest commit, so you don't have to compile it by yourself.

**Comment by petrk94** [comment]
@anna-wro thank you very much for including the compiled one
